class Listing
  attr_reader :id,
              :year,
              :make,
              :model,
              :trim,
              :body,
              :transmission,
              :vin,
              :state,
              :condition,
              :odometer,
              :color,
              :interior,
              :selling_price,
              :title,
              :data_hash

  def initialize(data = {})
    @id = data[:id]
    @year = data[:year]
    @make = data[:make]
    @model = data[:model]
    @trim = data[:trim]
    @body = data[:body]
    @transmission = data[:transmission]
    @vin = data[:vin]
    @state = data[:state]
    @condition = data[:condition]
    @odometer = data[:odometer]
    @color = data[:color]
    @interior = data[:interior]
    @selling_price = data[:sellingprice]
    @title = "#{@year} #{@make} #{@model}"

    data[:title] = @title
    @data_hash = data
  end

  def self.all_makes
    ["Acura",
    "Audi",
    "BMW",
    "Cadillac",
    "Land Rover",
    "Mazda",
    "Nissan",
    "Subaru",
    "Volkswagen"]
  end

  def self.all_models
    [["Acura: CL","CL"],
    ["Acura: ILX","ILX"],
    ["Acura: MDX","MDX"],
    ["Acura: RDX","RDX"],
    ["Acura: RL","RL"],
    ["Acura: RLX","RLX"],
    ["Acura: RSX","RSX"],
    ["Acura: TL","TL"],
    ["Acura: TSX","TSX"],
    ["Acura: TSX Sport Wagon","TSX Sport Wagon"],
    ["Acura: ZDX","ZDX"],
    ["Audi: A3","A3"],
    ["Audi: A4","A4"],
    ["Audi: A5","A5"],
    ["Audi: A6","A6"],
    ["Audi: A7","A7"],
    ["Audi: A8","A8"],
    ["Audi: allroad","allroad"],
    ["Audi: allroad quattro","allroad quattro"],
    ["Audi: Q5","Q5"],
    ["Audi: Q7","Q7"],
    ["Audi: R8","R8"],
    ["Audi: RS 5","RS 5"],
    ["Audi: RS 6","RS 6"],
    ["Audi: RS 7","RS 7"],
    ["Audi: S4","S4"],
    ["Audi: S5","S5"],
    ["Audi: S6","S6"],
    ["Audi: S7","S7"],
    ["Audi: S8","S8"],
    ["Audi: SQ5","SQ5"],
    ["Audi: TT","TT"],
    ["Audi: TT RS","TT RS"],
    ["Audi: TTS","TTS"],
    ["BMW: 1 Series","1 Series"],
    ["BMW: 2 Series","2 Series"],
    ["BMW: 3 Series","3 Series"],
    ["BMW: 3 Series Gran Turismo","3 Series Gran Turismo"],
    ["BMW: 4 Series","4 Series"],
    ["BMW: 4 Series Gran Coupe","4 Series Gran Coupe"],
    ["BMW: 5 Series","5 Series"],
    ["BMW: 5 Series Gran Turismo","5 Series Gran Turismo"],
    ["BMW: 6 Series","6 Series"],
    ["BMW: 6 Series Gran Coupe","6 Series Gran Coupe"],
    ["BMW: 7 Series","7 Series"],
    ["BMW: ActiveHybrid 5","ActiveHybrid 5"],
    ["BMW: ActiveHybrid 7","ActiveHybrid 7"],
    ["BMW: ActiveHybrid X6","ActiveHybrid X6"],
    ["BMW: M","M"],
    ["BMW: M3","M3"],
    ["BMW: M4","M4"],
    ["BMW: M5","M5"],
    ["BMW: M6","M6"],
    ["BMW: X1","X1"],
    ["BMW: X3","X3"],
    ["BMW: X4","X4"],
    ["BMW: X5","X5"],
    ["BMW: X5 M","X5 M"],
    ["BMW: X6","X6"],
    ["BMW: X6 M","X6 M"],
    ["BMW: Z3","Z3"],
    ["BMW: Z4","Z4"],
    ["Cadillac: ATS","ATS"],
    ["Cadillac: Catera","Catera"],
    ["Cadillac: CTS","CTS"],
    ["Cadillac: CTS Coupe","CTS Coupe"],
    ["Cadillac: CTS Wagon","CTS Wagon"],
    ["Cadillac: CTS-V","CTS-V"],
    ["Cadillac: CTS-V Coupe","CTS-V Coupe"],
    ["Cadillac: CTS-V Wagon","CTS-V Wagon"],
    ["Cadillac: DeVille","DeVille"],
    ["Cadillac: DTS","DTS"],
    ["Cadillac: Eldorado","Eldorado"],
    ["Cadillac: ELR","ELR"],
    ["Cadillac: Escalade","Escalade"],
    ["Cadillac: Escalade ESV","Escalade ESV"],
    ["Cadillac: Escalade EXT","Escalade EXT"],
    ["Cadillac: Escalade Hybrid","Escalade Hybrid"],
    ["Cadillac: Seville","Seville"],
    ["Cadillac: SRX","SRX"],
    ["Cadillac: STS","STS"],
    ["Cadillac: XLR","XLR"],
    ["Cadillac: XTS","XTS"],
    ["Land Rover: Discovery","Discovery"],
    ["Land Rover: Discovery Series II","Discovery Series II"],
    ["Land Rover: Freelander","Freelander"],
    ["Land Rover: LR2","LR2"],
    ["Land Rover: LR3","LR3"],
    ["Land Rover: LR4","LR4"],
    ["Land Rover: Range Rover","Range Rover"],
    ["Land Rover: Range Rover Evoque","Range Rover Evoque"],
    ["Land Rover: Range Rover Sport","Range Rover Sport"],
    ["Mazda: 6","6"],
    ["Mazda: CX-5","CX-5"],
    ["Mazda: CX-7","CX-7"],
    ["Mazda: CX-9","CX-9"],
    ["Mazda: Mazda2","Mazda2"],
    ["Mazda: Mazda3","Mazda3"],
    ["Mazda: Mazda5","Mazda5"],
    ["Mazda: Mazda6","Mazda6"],
    ["Mazda: Mazdaspeed 3","Mazdaspeed 3"],
    ["Mazda: Mazdaspeed Mazda3","Mazdaspeed Mazda3"],
    ["Mazda: Mazdaspeed Mazda6","Mazdaspeed Mazda6"],
    ["Mazda: Mazdaspeed3","Mazdaspeed3"],
    ["Mazda: Millenia","Millenia"],
    ["Mazda: MPV","MPV"],
    ["Mazda: MX-5 Miata","MX-5 Miata"],
    ["Mazda: Protege","Protege"],
    ["Mazda: Protege5","Protege5"],
    ["Mazda: Tribute","Tribute"],
    ["Nissan: 350Z","350Z"],
    ["Nissan: 370Z","370Z"],
    ["Nissan: Altima","Altima"],
    ["Nissan: Altima Hybrid","Altima Hybrid"],
    ["Nissan: Armada","Armada"],
    ["Nissan: Cube","Cube"],
    ["Nissan: Frontier","Frontier"],
    ["Nissan: GT-R","GT-R"],
    ["Nissan: Juke","Juke"],
    ["Nissan: Leaf","Leaf"],
    ["Nissan: Maxima","Maxima"],
    ["Nissan: Murano","Murano"],
    ["Nissan: Murano CrossCabriolet","Murano CrossCabriolet"],
    ["Nissan: NV","NV"],
    ["Nissan: NV Cargo","NV Cargo"],
    ["Nissan: NV200","NV200"],
    ["Nissan: Pathfinder","Pathfinder"],
    ["Nissan: Quest","Quest"],
    ["Nissan: Rogue","Rogue"],
    ["Nissan: Rogue Select","Rogue Select"],
    ["Nissan: Sentra","Sentra"],
    ["Nissan: Titan","Titan"],
    ["Nissan: Truck","Truck"],
    ["Nissan: Versa","Versa"],
    ["Nissan: Versa Note","Versa Note"],
    ["Nissan: Xterra","Xterra"],
    ["Subaru: B9 Tribeca","B9 Tribeca"],
    ["Subaru: Baja","Baja"],
    ["Subaru: BRZ","BRZ"],
    ["Subaru: Forester","Forester"],
    ["Subaru: Impreza","Impreza"],
    ["Subaru: Impreza WRX","Impreza WRX"],
    ["Subaru: Legacy","Legacy"],
    ["Subaru: Outback","Outback"],
    ["Subaru: Tribeca","Tribeca"],
    ["Subaru: XV Crosstrek","XV Crosstrek"],
    ["Volkswagen: Beetle","Beetle"],
    ["Volkswagen: Beetle Convertible","Beetle Convertible"],
    ["Volkswagen: Cabrio","Cabrio"],
    ["Volkswagen: CC","CC"],
    ["Volkswagen: Eos","Eos"],
    ["Volkswagen: GLI","GLI"],
    ["Volkswagen: Golf","Golf"],
    ["Volkswagen: Golf GTI","Golf GTI"],
    ["Volkswagen: Golf R","Golf R"],
    ["Volkswagen: GTI","GTI"],
    ["Volkswagen: Jetta","Jetta"],
    ["Volkswagen: Jetta GLI","Jetta GLI"],
    ["Volkswagen: Jetta Hybrid","Jetta Hybrid"],
    ["Volkswagen: Jetta SportWagen","Jetta SportWagen"],
    ["Volkswagen: New Beetle","New Beetle"],
    ["Volkswagen: Passat","Passat"],
    ["Volkswagen: Phaeton","Phaeton"],
    ["Volkswagen: R32","R32"],
    ["Volkswagen: Rabbit","Rabbit"],
    ["Volkswagen: Routan","Routan"],
    ["Volkswagen: Tiguan","Tiguan"],
    ["Volkswagen: Touareg","Touareg"],
    ["Volkswagen: Touareg 2","Touareg 2"]]
  end
end
